name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - disabled

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.8'

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Blazor app
      run: dotnet publish -c Release -o publish

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish/wwwroot
